config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check

  resources :presentations do
    resources :evaluations
  end

  
  resources :presentations do
    member do
      patch :update_grade
    end
  end


  # Defines the root path route ("/")
  root "presentations#index"

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
    belongs_to :presentation
    belongs_to :user

    validates :points, :feedback, presence: true
end

app/models/presentation.rb
class Presentation < ApplicationRecord
    belongs_to :user
    has_many :evaluations, dependent: :destroy

    validates :title, :description, :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :presentations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_evaluation, only: %i[ show edit update destroy ]
    before_action :set_presentation, only: %i[ create edit show update destroy ]

    def show
    end

    def create
        @evaluation = @presentation.evaluations.create(params[:evaluation].permit(:points, :feedback, :presentation_id))
        @evaluation.user_id = current_user.id
        respond_to do |format|
            if @evaluation.save
                format.html { redirect_to presentation_url(@presentation)}
                format.js
            else
                format.html { redirect_to presentation_url(@presentation), notice: "Evaluation was not created." }
                format.js
            end
        end
    end

    def new
    end

    def destroy
        @evaluation = @presentation.evaluations.find(params[:id])
        @evaluation.destroy
        redirect_to presentation_path(@presentation)
    end

    def edit
        @presentation = Presentation.find(params[:presentation_id])
        @evaluation = @presentation.evaluations.find(params[:id])
    end

    def update
        @evaluation = @presentation.evaluations.find(params[:id])
        respond_to do |format|
            if @evaluation.update(evaluation_params)
                format.html { redirect_to presentation_url(@presentation), notice: "Evaluation was successfully updated." }
                format.json { render :show, status: :ok, location: @evaluation }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @evaluation.errors, status: :unprocessable_entity }
            end
        end
    end

    private

    def set_evaluation
        @evaluation = Evaluation.find(params[:id])
    end

    def set_presentation
        @presentation = Presentation.find(params[:presentation_id])
    end

    def evaluation_params
        params.require(:evaluation).permit(:points, :feedback)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation , only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /presentations or /presentations.json
  def index
    @presentations = Presentation.all

    if current_user.admin?
      render 'admin'
    else
      render 'user'
    end
  end

  # GET /presentations/1 or /presentations/1.json
  def show
    @presentations = Presentation.all
  end

  # GET /presentations/new
  def new
    @presentation = current_user.presentations.build
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations or /presentations.json
  def create
    @presentation = current_user.presentations.build(presentation_params)
    puts @presentation
    respond_to do |format|
      if @presentation.save
        format.html { redirect_to presentations_path, notice: "Presentation was successfully created." }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1 or /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to presentation_url(@presentation), notice: "Presentation was successfully updated." }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1 or /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


def update_grade
  @presentation = Presentation.find(params[:id])
  if @presentation.update(grade_params)
    redirect_to @presentation, notice: 'Grade was successfully updated.'
  else
    render :edit, alert: 'Failed to update grade.'
  end
end

private

def grade_params
  params.require(:presentation).permit(:grade)
end

before_action :check_admin, only: [:update_grade]

def check_admin
  redirect_to(root_url, alert: "You are not authorized to perform this action.") unless current_user.admin?
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def presentation_params
      params.require(:presentation).permit(:title, :description, :date)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation,:admin)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/evaluations/_evaluation.html.erb
<hr class="h-px bg-gray-200 border-0">
<div class="flex flex-col gap-4">
  <div class="flex justify-between items-center">
    <div class = "flex gap-4">
      <%= render 'shared/avatar', letter: evaluation.user.name[0].upcase, id: evaluation.user_id%>
      <div>
        <p>
          <span class="font-semibold">
            <%=evaluation.user.name.capitalize%>
          </span>
          evaluated <%= evaluation.created_at.strftime("%A, %B %d, %Y")%>
        </p>
        <p class = "text-gray-500">Score: <%=evaluation.points%> points</p>
      </div>
    </div>
    <div class="flex gap-4">
      <%if current_user == evaluation.user%>
        <%= link_to edit_presentation_evaluation_path(evaluation.presentation, evaluation),
                  method: :delete, data: {confirm: "Are you sure ?" } do %>
          <i class="fa fa-pencil fa-lg"></i>
        <%end%>
      <%end%>
      <%if current_user.admin? || current_user == evaluation.user%>
        <%= button_to [evaluation.presentation, evaluation],
            method: :delete, data: {confirm: "Are you sure ?" } do %>
          <i class="fa fa-trash-o fa-lg"></i>
        <%end%>
      <%end%>
    </div>
  </div>
  <p class = "text-gray-500"><%=evaluation.feedback%></p>
</div>

app/views/evaluations/_form.html.erb
<h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900">Add Evaluation</h1>
<%= simple_form_for([@presentation, Evaluation.new], remote: true) do |f| %>
  <div class="flex flex-col gap-4">
    <%= f.input :feedback,           
          required: true, 
          autofocus: true,
          input_html: {class: "form-input h-36" },
          label_html: { class: "form-label" } %>
    <%= f.input :points, required: true, 
          input_html: { class: 'form-input' },
          label_html: { class: "form-label" } %>
  </div>
  <%= f.button :submit, "Submit evaluation", class: "mt-8 text-base text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg px-5 py-3 text-center" %>
<% end %>

app/views/evaluations/edit.html.erb
<div class="flex items-center justify-center">
  <div class="flex flex-col gap-5 w-[50rem] rounded-lg px-10 py-8 shadow-md  justify-center bg-white">
    <%= link_to @presentation, class:"text-xl font-medium text-blue-600" do %>
      <i class="fa fa-arrow-left"></i> <strong>Back</strong>
    <% end %>
    <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900">Edit Evaluation</h1>
    <%= simple_form_for([@presentation, @evaluation], remote: true) do |f| %>
      <div class="flex flex-col gap-4">
        <%= f.input :feedback,           
          required: true, 
          autofocus: true,
          input_html: {class: "form-input h-36" },
          label_html: { class: "form-label" } %>
        <%= f.input :points, required: true, 
          input_html: { class: 'form-input' },
          label_html: { class: "form-label" } %>
      </div>
      <%= f.button :submit, "Submit", class: "w-full mt-8 text-base text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg px-5 py-3 text-center" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discussions</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@40,400,0,0" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="min-h-screen bg-[#f9fafb] pb-12">
    <nav class="flex justify-between items-center flex-wrap px-16 py-4 w-full border-b bg-white">
      <h2 class="flex-none text-2xl font-semibold">Presentations</h2>
      <% if user_signed_in? %>
        <div class="relative inline-block text-left text-gray-700" id="dropdown">
          <button type="button" class="flex items-center gap-2 text-lg font-semibold px-3 py-2" id="menu-button">
            Welcome <%= current_user.name.split(" ")[0].capitalize %>
            <svg class="w-2.5 h-2.5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
            </svg>
          </button>
          <div class="hidden absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" id="dropdown-content">
            <% if current_user.admin? %>
              <p class="block px-4 py-2 font-semibold text-blue-600 border-b-2">Admin</p>
            <% end %>
            <%= link_to "Account Settings", edit_user_registration_path, class: "block px-4 py-2" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "block px-4 py-2" %>
          </div>
        </div>
      <% else %>
        <div class="flex gap-6">
          <%= link_to "Sign In", new_user_session_path, class: "block px-4 py-2" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "block px-4 py-2" %>
        </div>
      <% end %>
    </nav>
    <!-- Flash messages for notice and alert -->
    <% if flash[:notice] %>
      <div class="bg-green-500 text-white px-4 py-3">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="bg-red-500 text-white px-4 py-3">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <section class="pt-8">
      <%= yield %> <!-- This is where content from other views is injected -->
    </section>
  </body>
</html>

app/views/old/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/old/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/presentations/_form.html.erb
<div class="flex items-center justify-center ">
  <div class="flex flex-col gap-5 w-[50rem] rounded-lg px-10 py-12 shadow-md  justify-center bg-white">
    <%= link_to presentations_path, class:"text-xl font-medium text-blue-600" do %>
      <i class="fa fa-arrow-left"></i> <strong>Back</strong>
    <% end %>
    <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900"><%=action%> presentation</h1>
    <%= simple_form_for(@presentation) do |f| %>
      <div class="flex flex-col gap-4">
        <%= f.input :title,
          required: true, 
          autofocus: true,
          input_html: {class: "form-input" },
          label_html: { class: "form-label" } %>
        <%= f.input :description,           
          required: true, 
          autofocus: true,
          input_html: {class: "form-input h-48" },
          label_html: { class: "form-label" } %>
        <%= f.input :date, required: true, label: 'Presentation Date', as: :date, 
          input_html: { class: 'bg-gray-50 border border-gray-300 text-gray-900 text-base rounded-lg' },
          label_html: { class: "form-label" } %>
      </div>
      <%= f.button :submit, "Submit", class: "mt-8 w-full text-base text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg px-5 py-3 text-center" %>
    <% end %>
  </div>
</div>

app/views/presentations/admin.html.erb
<div class="flex justify-center">
  <div class = "w-3/4 w-max-[125rem]">
    <div class="flex mb-8">
      <%= link_to "Create a Presentation", new_presentation_path, class: "px-12 py-3 bg-blue-600 box-border rounded-md text-white font-semibold" %>
    </div>
    <div class = "flex gap-6 flex-col">
      <%= render 'shared/presentation', presentations: @presentations %>
    </div>
  </div>
</div>

app/views/presentations/edit.html.erb
<%= render "form", presentation: @presentation, action: "Edit" %>

app/views/presentations/index.html.erb
<%# Redirection screen%>

app/views/presentations/new.html.erb
<%= render "form", presentation: @presentation, action: "Create" %>

app/views/presentations/show.html.erb
<div class="flex items-center justify-center w-full">
  <div class="flex flex-col gap-5 w-3/4 w-max-[125rem] rounded-lg px-10 py-8 shadow-md  justify-center bg-white">
    <%= link_to presentations_path, class:"text-xl font-medium text-blue-600" do %>
      <i class="fa fa-arrow-left"></i> <strong>Back</strong>
    <% end %>
    <div class="flex flex-col">
      <div class="flex justify-between items-center">
        <div class = "flex gap-4 items-center">
          <%= render 'shared/avatar', letter: @presentation.user.name[0].upcase, id: @presentation.user_id%>
          <div>
            <h1 class="font-semibold text-xl"><%= @presentation.user.name.capitalize %></h1>
            <p class="text-gray-500"><%= @presentation.date.strftime("%A, %B %d, %Y") %></p>
          </div>
        </div>
        <% if @presentation.user == current_user || current_user.admin? %>
          <div class="flex gap-4 items-center justify-center">
            <%= link_to edit_presentation_path(@presentation),
                  method: :delete, data: {confirm: "Are you sure ?" } do %>
              <i class="fa fa-pencil fa-lg"></i>
            <%end%>
            <%= button_to @presentation,
            method: :delete, data: {confirm: "Are you sure ?" } do %>
              <i class="fa fa-trash-o fa-lg"></i>
            <%end%>
          </div>
        <%end%>
      </div>
      <h1 class = "font-semibold text-2xl mt-4"><%=@presentation.title.capitalize%></h1>
      <p class = "text-gray-500"><%=@presentation.description%></p>
    </div>
    <% if @presentation.user == current_user || current_user.admin? %>
      <% if current_user.admin? %>
        <%= simple_form_for @presentation, url: update_grade_presentation_path(@presentation), method: :patch do |f| %>
          <div class="flex items-center">
            <span class="font-bold mr-2 text-lg">Grade:</span>
            <%= f.input :grade, collection: ['N/A', 'A', 'B', 'C', 'D', 'F'], selected: @presentation.grade, label: false, input_html: { class: "block py-2.5 text-sm text-gray-500 bg-transparent border-0 border-b-2 border-gray-200 appearance-none" } %>
          </div>
          <%= f.button :submit, "Set Grade", class: "mt-4 text-sm text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg px-3 py-2 text-center" %>
        <% end %>
      <% else %>
        <div class="flex items-center">
          <span class="font-bold mr-2 text-lg">Grade:</span><%= @presentation.grade || "N/A" %>
        </div>
      <% end %>
    <% end %>
    <% if @presentation.user != current_user || current_user.admin? %>
      <hr class="h-px bg-gray-200 border-0 my-4">
      <%= render 'evaluations/form' %>
    <% end %>
  </div>
</div>
<div class="flex items-center justify-center w-full mt-4">
  <div class="flex flex-col gap-5 w-3/4 w-max-[125rem] rounded-lg px-10 py-8 shadow-md bg-white justify-center">
    <div class="flex items-center">
      <h1 class="font-semibold text-2xl pr-6">Evaluations</h1>
      <i class="material-symbols-outlined text-gray-500 pr-1">forum</i>
      <p class="text-gray-500">
        <%= pluralize(@presentation.evaluations.count, 'Evaluation') %>
      </p>
    </div>
    <% if @presentation.user == current_user || current_user.admin?%>
      <%= render @presentation.evaluations%>
    <% else %>
      <%= render @presentation.evaluations.where(user_id: current_user.id)%>
    <% end %>
  </div>
</div>

app/views/presentations/user.html.erb
<div class="flex justify-center">
  <div class = "w-3/4 w-max-[125rem]">
    <div class="flex mb-8">
      <%= link_to "Create a Presentation", new_presentation_path, class: "px-12 py-3 bg-blue-600 box-border rounded-md text-white font-semibold" %>
    </div>
    <div class = "flex gap-6 flex-col">
      <%= render 'shared/presentation', presentations: @presentations %>
    </div>
  </div>
</div>

app/views/shared/_avatar.html.erb
<%colors = %w(#f2b736 #c5523f #499255 #1875e5).freeze%>
<%puts colors[id%colors.length]%>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 50 50" class="rounded-md">
  <rect width="100%" height="100%" fill="<%=colors[id%colors.length]%>"/>
  <text fill="#fff" font-family="Helvetica,Arial,sans-serif" font-size="26" font-weight="500" x="50%" y="55%" dominant-baseline="middle" text-anchor="middle">
    <%= letter %>
  </text>
  </svg>

app/views/shared/_presentation.html.erb
<% my_presentations, other_presentations = presentations.partition { |presentation| presentation.user == current_user } %>
<% my_presentations.each do |presentation| %>
  <%= link_to presentation do %>
    <div class="w-full flex justify-between bg-white shadow-md hover:bg-[#eff1f1] p-6 rounded-md">
      <div class="w-full flex flex-col gap-4">
        <div class = "flex gap-4 items-center">
          <%= render 'shared/avatar', letter: presentation.user.name[0].upcase, id: presentation.user_id%>
          <div>
            <h1 class = "font-semibold text-xl"><%=presentation.title.capitalize%></h1>
            <p class="text-gray-500">
              <span class="font-semibold">
                <%=presentation.user.name.capitalize%>
              </span>
              presents on <%= presentation.date.strftime("%A, %B %d, %Y")%>
            </p>
          </div>
        </div>
        <hr class="h-px bg-gray-200 border-0">
        <p class = "text-gray-500"><%=presentation.description%></p>
      </div>
    </div>
  <% end %>
<% end %>
<% other_presentations.each do |presentation| %>
  <%= link_to presentation do %>
    <div class="w-full flex justify-between bg-white shadow-md hover:bg-[#eff1f1] p-6 rounded-md">
      <div class="w-full flex flex-col gap-4">
        <div class = "flex gap-4 items-center">
          <%= render 'shared/avatar', letter: presentation.user.name[0].upcase, id: presentation.user_id%>
          <div>
            <h1 class = "font-semibold text-xl"><%=presentation.title.capitalize%></h1>
            <p class="text-gray-500">
              <span class="font-semibold">
                <%=presentation.user.name.capitalize%>
              </span>
              presents on <%= presentation.date.strftime("%A, %B %d, %Y")%>
            </p>
          </div>
        </div>
        <hr class="h-px bg-gray-200 border-0">
        <p class = "text-gray-500"><%=presentation.description%></p>
      </div>
    </div>
  <% end %>
<% end %>